<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="2">

  <testsuite name="test"
    errors="1" failures="0" hostname="" id="" package="test" skipped="1"
    tests="2" time="0.006000" timestamp="Thu, 02 May 2019 20:18:44 GMT">
  
    <testcase name="Test for Login" classname="test" time="0.006000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Test / Test for Login]:

  ReferenceError: username is not defined
    at Object.Test for Login (C:\Users\dburdyga\WebstormProjects\my_project\tests\e2e\specs\test.js:10:46)
    at Module.call (C:\Users\dburdyga\WebstormProjects\my_project\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\dburdyga\WebstormProjects\my_project\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\dburdyga\WebstormProjects\my_project\node_modules\q\q.js:834:54)
    at C:\Users\dburdyga\WebstormProjects\my_project\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\dburdyga\WebstormProjects\my_project\node_modules\q\q.js:796:13)
    at C:\Users\dburdyga\WebstormProjects\my_project\node_modules\q\q.js:556:49
    at runSingle (C:\Users\dburdyga\WebstormProjects\my_project\node_modules\q\q.js:137:13)
    at flush (C:\Users\dburdyga\WebstormProjects\my_project\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    </system-err>
  

  
    
    <testcase
      name="Test for Registration" classname="test">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
